/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮本项目遵循技术中立原则，使用者须严格遵守国家相关法律法规，严禁用于任何危害国家安全、破坏社会稳定或侵犯他人合法权益的行为。任何基于本项目的二次开发、修改、分发或实际部署所引发的法律纠纷、行政处罚及侵权赔偿，均由相关行为人自行承担全部法律责任，本团队不承担任何形式的连带责任。</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FinishStatusEnum } from './finish-status-enum';
 /**
 * 
 *
 * @export
 * @interface AddScheduleInput
 */
export interface AddScheduleInput {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof AddScheduleInput
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof AddScheduleInput
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    updateUserName?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    tenantId?: number | null;

    /**
     * 用户Id
     *
     * @type {number}
     * @memberof AddScheduleInput
     */
    userId?: number;

    /**
     * 日程日期
     *
     * @type {Date}
     * @memberof AddScheduleInput
     */
    scheduleTime?: Date | null;

    /**
     * 开始时间
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    startTime?: string | null;

    /**
     * 结束时间
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    endTime?: string | null;

    /**
     * @type {FinishStatusEnum}
     * @memberof AddScheduleInput
     */
    status?: FinishStatusEnum;

    /**
     * 日程内容
     *
     * @type {string}
     * @memberof AddScheduleInput
     */
    content: string;
}
