/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮本项目遵循技术中立原则，使用者须严格遵守国家相关法律法规，严禁用于任何危害国家安全、破坏社会稳定或侵犯他人合法权益的行为。任何基于本项目的二次开发、修改、分发或实际部署所引发的法律纠纷、行政处罚及侵权赔偿，均由相关行为人自行承担全部法律责任，本团队不承担任何形式的连带责任。</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * GPU信息
 *
 * @export
 * @interface GpuInfo
 */
export interface GpuInfo {

    /**
     * GPU名称
     *
     * @type {string}
     * @memberof GpuInfo
     */
    name?: string | null;

    /**
     * 描述
     *
     * @type {string}
     * @memberof GpuInfo
     */
    description?: string | null;

    /**
     * 厂商
     *
     * @type {string}
     * @memberof GpuInfo
     */
    vendor?: string | null;

    /**
     * 设备ID
     *
     * @type {string}
     * @memberof GpuInfo
     */
    deviceId?: string | null;

    /**
     * 总线信息
     *
     * @type {string}
     * @memberof GpuInfo
     */
    busInfo?: string | null;

    /**
     * 驱动版本
     *
     * @type {string}
     * @memberof GpuInfo
     */
    driverVersion?: string | null;

    /**
     * 显存大小（字节）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    memoryBytes?: number;

    /**
     * GPU温度（°C）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    temperature?: number | null;

    /**
     * 视频模式描述
     *
     * @type {string}
     * @memberof GpuInfo
     */
    videoModeDescription?: string | null;

    /**
     * 状态
     *
     * @type {string}
     * @memberof GpuInfo
     */
    status?: string | null;

    /**
     * GPU使用率（%）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    utilizationPercentage?: number | null;

    /**
     * 显存使用率（%）
     *
     * @type {number}
     * @memberof GpuInfo
     */
    memoryUtilizationPercentage?: number | null;
}
