/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮本项目遵循技术中立原则，使用者须严格遵守国家相关法律法规，严禁用于任何危害国家安全、破坏社会稳定或侵犯他人合法权益的行为。任何基于本项目的二次开发、修改、分发或实际部署所引发的法律纠纷、行政处罚及侵权赔偿，均由相关行为人自行承担全部法律责任，本团队不承担任何形式的连带责任。</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { Search } from './search';
 /**
 * 
 *
 * @export
 * @interface PageExLogInput
 */
export interface PageExLogInput {

    /**
     * @type {Search}
     * @memberof PageExLogInput
     */
    search?: Search;

    /**
     * 模糊查询关键字
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    keyword?: string | null;

    /**
     * @type {Filter}
     * @memberof PageExLogInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof PageExLogInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof PageExLogInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    descStr?: string | null;

    /**
     * 开始时间
     *
     * @type {Date}
     * @memberof PageExLogInput
     */
    startTime?: Date | null;

    /**
     * 结束时间
     *
     * @type {Date}
     * @memberof PageExLogInput
     */
    endTime?: Date | null;

    /**
     * 账号
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    account?: string | null;

    /**
     * 操作用时
     *
     * @type {number}
     * @memberof PageExLogInput
     */
    elapsed?: number | null;

    /**
     * 状态
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    status?: string | null;

    /**
     * IP地址
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    remoteIp?: string | null;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof PageExLogInput
     */
    tenantId?: number;

    /**
     * 方法名称
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    actionName?: string | null;

    /**
     * 模块名称
     *
     * @type {string}
     * @memberof PageExLogInput
     */
    controllerName?: string | null;
}
