/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮本项目遵循技术中立原则，使用者须严格遵守国家相关法律法规，严禁用于任何危害国家安全、破坏社会稳定或侵犯他人合法权益的行为。任何基于本项目的二次开发、修改、分发或实际部署所引发的法律纠纷、行政处罚及侵权赔偿，均由相关行为人自行承担全部法律责任，本团队不承担任何形式的连带责任。</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 接口压测输出参数
 *
 * @export
 * @interface StressTestOutput
 */
export interface StressTestOutput {

    /**
     * 总请求次数
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    totalRequests?: number;

    /**
     * 总用时（秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    totalTimeInSeconds?: number;

    /**
     * 成功请求次数
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    successfulRequests?: number;

    /**
     * 失败请求次数
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    failedRequests?: number;

    /**
     * 每秒查询率（QPS）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    queriesPerSecond?: number;

    /**
     * 最小响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    minResponseTime?: number;

    /**
     * 最大响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    maxResponseTime?: number;

    /**
     * 平均响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    averageResponseTime?: number;

    /**
     * P10 响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile10ResponseTime?: number;

    /**
     * P25 响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile25ResponseTime?: number;

    /**
     * P50 响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile50ResponseTime?: number;

    /**
     * P75 响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile75ResponseTime?: number;

    /**
     * P90 响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile90ResponseTime?: number;

    /**
     * P99 响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile99ResponseTime?: number;

    /**
     * P999 响应时间（毫秒）
     *
     * @type {number}
     * @memberof StressTestOutput
     */
    percentile999ResponseTime?: number;
}
