/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮本项目遵循技术中立原则，使用者须严格遵守国家相关法律法规，严禁用于任何危害国家安全、破坏社会稳定或侵犯他人合法权益的行为。任何基于本项目的二次开发、修改、分发或实际部署所引发的法律纠纷、行政处罚及侵权赔偿，均由相关行为人自行承担全部法律责任，本团队不承担任何形式的连带责任。</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 系统文件表
 *
 * @export
 * @interface SysFile
 */
export interface SysFile {

    /**
     * 雪花Id
     *
     * @type {number}
     * @memberof SysFile
     */
    id?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof SysFile
     */
    createTime?: Date;

    /**
     * 更新时间
     *
     * @type {Date}
     * @memberof SysFile
     */
    updateTime?: Date | null;

    /**
     * 创建者Id
     *
     * @type {number}
     * @memberof SysFile
     */
    createUserId?: number | null;

    /**
     * 创建者姓名
     *
     * @type {string}
     * @memberof SysFile
     */
    createUserName?: string | null;

    /**
     * 修改者Id
     *
     * @type {number}
     * @memberof SysFile
     */
    updateUserId?: number | null;

    /**
     * 修改者姓名
     *
     * @type {string}
     * @memberof SysFile
     */
    updateUserName?: string | null;

    /**
     * 机构Id
     *
     * @type {number}
     * @memberof SysFile
     */
    orgId?: number;

    /**
     * 租户Id
     *
     * @type {number}
     * @memberof SysFile
     */
    tenantId?: number | null;

    /**
     * 提供者
     *
     * @type {string}
     * @memberof SysFile
     */
    provider?: string | null;

    /**
     * 仓储名称
     *
     * @type {string}
     * @memberof SysFile
     */
    bucketName?: string | null;

    /**
     * 文件名称（源文件名）
     *
     * @type {string}
     * @memberof SysFile
     */
    fileName?: string | null;

    /**
     * 文件后缀
     *
     * @type {string}
     * @memberof SysFile
     */
    suffix?: string | null;

    /**
     * 存储路径
     *
     * @type {string}
     * @memberof SysFile
     */
    filePath?: string | null;

    /**
     * 文件大小KB
     *
     * @type {number}
     * @memberof SysFile
     */
    sizeKb?: number;

    /**
     * 文件大小信息-计算后的
     *
     * @type {string}
     * @memberof SysFile
     */
    sizeInfo?: string | null;

    /**
     * 外链地址-OSS上传后生成外链地址方便前端预览
     *
     * @type {string}
     * @memberof SysFile
     */
    url?: string | null;

    /**
     * 文件MD5
     *
     * @type {string}
     * @memberof SysFile
     */
    fileMd5?: string | null;

    /**
     * 文件类别
     *
     * @type {string}
     * @memberof SysFile
     */
    fileType?: string | null;

    /**
     * 文件别名
     *
     * @type {string}
     * @memberof SysFile
     */
    fileAlias?: string | null;

    /**
     * 是否公开
     *
     * @type {boolean}
     * @memberof SysFile
     */
    isPublic?: boolean;

    /**
     * 业务数据Id
     *
     * @type {number}
     * @memberof SysFile
     */
    dataId?: number | null;
}
