allowBuilds:
  '@logicflow/core': true
  '@parcel/watcher': true
  '@vue-office/docx': true
  '@vue-office/excel': true
  '@vue-office/pdf': true
  core-js: true
  es5-ext: true
  json-editor-vue: true
  vue-demi: true
onlyBuiltDependencies:
  - '@vue-office/docx'
  - '@vue-office/excel'
  - '@vue-office/pdf'
packages:
  - .
